server:
  port: 8189
  servlet:
    context-path: /demo
jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 10m
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/springsecurity
    username: rootOrder
    password: masterkey
main:
  allow-circular-references: true
flyway:
  sqlMigrationSeparator: __
  validateOnMigrate: true
  validateMigrationNaming: false